# github.yml 
name: building_docker_github
description: ''

inputs:
  token:
    description: "GitHub Token used to authenticate against a repository for Git context."
    required: true
    default: '' 
  context:
    description: "Build's context is the set of files located in the specified PATH or URL (default Git context)"
    required: false
    default: './'
  file:
    description: "Path to the Dockerfile. (default {context}/Dockerfile)"
    required: false
    default: './Dockerfile'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: 'ghcr.io' 
        username: ${{ github.actor }}
          #        password: ${{ inputs.token }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1 
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
