# github.yml 
name: building_docker_github
description: ''

inputs:
  token:
    description: "GitHub Token used to authenticate against a repository for Git context."
    required: true
    default: '' 
  context:
    description: "Build's context is the set of files located in the specified PATH or URL (default Git context)"
    required: false
    default: './'
  file:
    description: "Path to the Dockerfile. (default {context}/Dockerfile)"
    required: false
    default: './Dockerfile'
  buildkit:
    description: "Enable docker buildkit"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64, linux/38
        driver: docker
        version: v0.8.0
        
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: 'ghcr.io' 
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        #flavor: |
        #  latest=false
          
    - name: Build Docker image
      shell: bash
      working-directory: "${{ inputs.context }}"
      if: ${{ inputs.buildkit == 'false' }}
      env:
        DOCKER_BUILDKIT: 0
      run: |
        cd ${{ inputs.context }};
        echo "${{ steps.meta.outputs.tags }}" | head -n 1
        
#docker build -t "${{ steps.meta.outputs.tags }}" -f ./Dockerfile .
#docker push "${{ steps.meta.outputs.tags }}"
        
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v6
#      with:
#        no-cache: true
#        context: ${{ inputs.context }}
#        file: ${{ inputs.file }}
#        push: true
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
