# github.yml 
name: building_docker_github
description: ''

inputs:
  token:
    description: ''
    required: true
  context:
    description: ''
    required: false
    default: '.'
  file: 
    description: ''
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: 'ghcr.io' 
        username: ${{ github.actor }}
        password: ${{ inputs.token || github.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: test 
      shell: bash
      run: | 
        echo ${{ inputs.context }}; 
        echo ${{ inputs.token }}; 
        echo ${{ inputs.file || format('{0}/{1}', inputs.context, 'Dockerfile') }}; 

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
