name: tagging 
description: ''

inputs:
  PAT:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: "${{ inputs.PAT || github.token }}"

    - uses: ./tagging/semver/major.yml@develop
      if: ${{ (github.event_name == 'workflow_dispatch' && github.actor) &&
              (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
      with:
        PAT: ${{ inputs.PAT }}

    - uses: ./tagging/semver/minor.yml@develop
      if: ${{ (github.event_name == 'push') &&
              (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
      with:
        PAT: ${{ inputs.PAT }}

    - uses: ./tagging/semver/patch.yml@develop
      if: ${{ startsWith(github.ref, 'refs/heads/fix/') && endsWith(github.ref, '.x') }}
      with:
        PAT: ${{ inputs.PAT }}
