# tagging.yml
name: tagging 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write

on:
  # Allow to re-use this jobs;   
  # Pass Private Access Token to allow 
  # create new-workflow for tag
  workflow_call:
    secrets:
      PAT:
        required: false 
        
  # Trigger minor update;
  # Trigger patch update;
  # Trigger on all branches;
  push:
    branches:
      - '*' 
   
  # Triger manualy;
  workflow_dispatch:

jobs:

  # SEMVER MAJOR
  semver-major:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
        # Restrict to manual startup; 
        # Restrict to default branch;
      - uses: ./tagging/semver/major.yml@develop
        if: ${{ (github.event_name == 'workflow_dispatch' && github.actor) &&
                (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
        with:
          PAT: ${{ secrets.PAT }}
  
  # -----------------
  # SEMVER MINOR
  # -----------------
  semver-minor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4 # Necessary to access local action
    # Restrict to push startup; 
    # Restrict to default branch;
    - uses: ./tagging/semver/minor.yml@develop
      if: ${{ (github.event_name == 'push') &&
              (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
      with:
        PAT: ${{ secrets.PAT }}
      
  # -----------------
  # SEMVER PATCH
  # -----------------
  semver-patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4 # Necessary to access local action
    # Restrict to the fix branch; 
    - uses: ./tagging/semver/patch.yml@develop
      if: ${{ startsWith(github.ref, 'refs/heads/fix/') && endsWith(github.ref, '.x') }}
      with:
        PAT: ${{ secrets.PAT }}
