name: patch 
description: ''

inputs:
  token:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: "${{ inputs.token || github.token }}"

    - name: Bump version
      shell: bash
      run: |
        GITHUB_REF=${GITHUB_REF//*\/}
        CURRENT_VERSION="$(git ls-remote -q --tags | awk '{ print $2}'| sort -nr | sed 's/refs\/tags\///g' | grep ${GITHUB_REF//.x} | head -n1 )";
        NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});

        git tag ${NEXT_VERSION};
        git push --tags origin;

