# building.yml
name: building_docker

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Allow to re-use this jobs;
  workflow_call:
  # Trigger on each push;
  push:
  # Triger manualy;
  workflow_dispatch:

jobs:

  # -----------------
  # SEMVER MAJOR
  # -----------------
  semver-major:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/building/docker/github
