# building.yml
name: Building Docker

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Allow to re-use this jobs;
  workflow_call:
    inputs:
      context:
        type: string
        default: '.'
        description: ''
      file:
        type: string
        default: "${{ inputs.context }}/Dockerfile"
        description: ''
    secretes:
      token:
        type: string
        default: "${{ github.token }}"
        description: ''

  # Trigger on each push;
  push:
  # Triger manualy;
  workflow_dispatch:

jobs:

  github:
    runs-on: ubuntu-latest
    steps:
      - uses: utilizable/github-actions/.github/actions/building/docker/github@develop
        with:
          token: "${{ secrets.PAT }}"
          context: ${{ inputs.context }} 
          file: ${{ inputs.file }}
