# tagging.yml
name: Tagging Semver

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write

on:
  # Allow to re-use this jobs;   
  # Pass Private Access Token to allow 
  # create new-workflow for new tag
  workflow_call:
    secrets:
      PAT:
        required: false 
        
  # Trigger minor update;
  # Trigger patch update;
  # Trigger on all branches;
  push:
    branches:
      - '*' 
   
  # Triger manualy;
  workflow_dispatch:

jobs:

  # -----------------
  # SEMVER MAJOR
  # -----------------
  major:
    # Restrict to manual startup; 
    # Restrict to default branch;
    if: ${{ (github.event_name == 'workflow_dispatch' && github.actor) &&
            (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Necessary to access local action
      - uses: utilizable/github-actions/.github/actions/tagging/semver/major
        with:
          PAT: ${{ secrets.PAT }}
  
  # -----------------
  # SEMVER MINOR
  # -----------------
  minor:
    # Restrict to push startup; 
    # Restrict to default branch;
    if: ${{ (github.event_name == 'push') &&
            (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Necessary to access local action
    - uses: utilizable/github-actions/.github/actions/tagging/semver/major
      with:
        PAT: ${{ secrets.PAT }}
      
  # -----------------
  # SEMVER PATCH
  # -----------------
  patch:
    # Restrict to the fix branch; 
    if: ${{ startsWith(github.ref, 'refs/heads/fix/') && endsWith(github.ref, '.x') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Necessary to access local action
    - uses: utilizable/github-actions/.github/actions/tagging/semver/major
      with:
        PAT: ${{ secrets.PAT }}

