# tagging.yml
name: tagging_semver

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write

on:
  # Allow to re-use this jobs;   
  # Pass Private Access Token to allow 
  # create new-workflow for tag
  workflow_call:
    secrets:
      PAT:
        required: false 
        
  # Trigger minor update;
  # Trigger patch update;
  # Trigger on all branches;
  push:
    branches:
      - '*' 
   
  # Triger manualy;
  workflow_dispatch:

jobs:

  # SEMVER MAJOR
  semver_major:
    # Restrict to manual startup; 
    # Restrict to default branch;
    if: ${{ (github.event_name == 'workflow_dispatch' && github.actor) &&
            (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
    uses: ./.github/workflows/tagging_semver_major.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}
      
  # -----------------
  # SEMVER MINOR
  # -----------------
  semver_minor:
    # Restrict to push startup; 
    # Restrict to default branch;
    if: ${{ (github.event_name == 'push') &&
            (always() && (format('refs/heads/{0}', github.event.repository.default_branch) == github.ref)) }}
    uses: ./.github/workflows/tagging_semver_minor.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}
      
  # -----------------
  # SEMVER PATCH
  # -----------------
  semver_patch:
    # Restrict to the fix branch; 
    if: ${{ startsWith(github.ref, 'refs/heads/fix/') && endsWith(github.ref, '.x') }}
    uses: ./.github/workflows/tagging_semver_patch.yml@develop
    secrets:
      PAT: ${{ secrets.PAT }}
